version: '3.9'

services:
  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - 80:80
    volumes:
      - ./frontend/public:/usr/share/nginx/html/public
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf

  node:
    container_name: node
    build:
      context: .
      dockerfile: ./docker/node/Dockerfile
    ports:
      - 9000:9000
    volumes:
      - ./backend:/app
    tty: true
